### ISSUE TITLE
Setup wechat login

### ISSUE THREAD

**Issue by litstrong** [litstrong/kkadda#12]
_From @litstrong on August 5, 2016 17:10_

_Copied from original issue: litstrong/bope#102_

**Comment by litstrong** [comment]
https://wohugb.gitbooks.io/wechat/content/authorize/step_two.html

**Comment by litstrong** [comment]
Will be better to create an app `auth` to put these stuffs.

**Comment by litstrong** [comment]
new `auth` is taken in #65 .

**Comment by litstrong** [comment]
https://github.com/weflex/react-native-wechat

**Comment by litstrong** [comment]
https://github.com/weflex/react-native-wechat/blob/master/index.js#L138

**Comment by litstrong** [comment]
https://github.com/beefe/react-native-wechat-ios

**Comment by litstrong** [comment]
https://github.com/beefe/react-native-wechat-android

**Comment by litstrong** [comment]
Tried:
http://dev.wechat.com/wechatapi/installguide

**Comment by picodoth** [comment]
wechat auth was done in this PR: https://github.com/litstrong/kkadda/pull/68

**Comment by picodoth** [comment]
checkout http://admin.wechat.com/wiki/index.php?title=User_Profile_via_Web for further api

**Comment by picodoth** [comment]
more info after authorization: https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419317853&token=&lang=zh_CN
