### ISSUE TITLE
Add event punch activity api

### ISSUE THREAD

**Issue by picodoth** [litstrong/kkadda#33]
to unblock #32
Given an event, clicking on punch times will return a list of punch activity, with the following info for each punch activity:
1. user info, including avatar
2. time
3. punching picture
4. punching description

**Comment by litstrong** [comment]
`enrollment_count` and `punchinfo_count`

**Comment by litstrong** [comment]
Before we have a performance issue, we'll put all enrollment info and punch info in the event list response.
